package com.example.qskip.admin.products

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import coil.compose.AsyncImage
import com.example.qskip.utils.QrDownloadUtil

fun generateProductCode(name: String, color: String, size: String): String {
    val cleanName = name.trim().uppercase().replace(Regex("[^A-Z0-9]+"), "-").trim('-')
    val cleanColor = color.trim().uppercase().replace(Regex("[^A-Z0-9]+"), "")
    val cleanSize = size.trim().uppercase().replace(Regex("[^A-Z0-9]+"), "")

    if (cleanName.isBlank()) return ""

    val parts = mutableListOf(cleanName)
    if (cleanColor.isNotBlank()) parts.add(cleanColor)
    if (cleanSize.isNotBlank()) parts.add(cleanSize)

    return parts.joinToString("-")
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AdminAddProductScreen(
    productId: String? = null,
    onNavigateBack: () -> Unit,
    viewModel: AdminProductViewModel = hiltViewModel()
) {
    val context = LocalContext.current
    val uiState by viewModel.uiState.collectAsState()

    var name by remember { mutableStateOf("") }
    var category by remember { mutableStateOf("") }
    var size by remember { mutableStateOf("") }
    var color by remember { mutableStateOf("") }
    var priceInput by remember { mutableStateOf("") }
    var stockInput by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var active by remember { mutableStateOf(true) }
    var existingImageUrls by remember { mutableStateOf<List<String>>(emptyList()) }
    var validationError by remember { mutableStateOf<String?>(null) }

    // Auto-generated Product Code from Name, Color & Size
    val autoGeneratedCode = remember(name, color, size) {
        generateProductCode(name, color, size)
    }

    // Image Picker State
    var selectedImageUri by remember { mutableStateOf<Uri?>(null) }
    var imageBytes by remember { mutableStateOf<ByteArray?>(null) }

    val imagePickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        selectedImageUri = uri
        if (uri != null) {
            val bytes = context.contentResolver.openInputStream(uri)?.use { it.readBytes() }
            imageBytes = bytes
        }
    }

    // Load existing product if editing
    LaunchedEffect(productId) {
        if (!productId.isNullOrBlank()) {
            viewModel.loadProductForEdit(productId)
        }
    }

    // Populate state when editingProduct changes
    LaunchedEffect(uiState.editingProduct) {
        uiState.editingProduct?.let { p ->
            name = p.name
            category = p.categoryId
            size = p.size
            color = p.color
            priceInput = p.price.toString()
            stockInput = p.stockQuantity.toString()
            description = p.description
            active = p.active
            existingImageUrls = p.imageUrls
        }
    }

    LaunchedEffect(uiState.isSaveSuccess) {
        if (uiState.isSaveSuccess) {
            viewModel.resetSaveState()
            onNavigateBack()
        }
    }

    val isEditMode = !productId.isNullOrBlank()
    val displayError = validationError ?: uiState.error

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (isEditMode) "Edit Product" else "Add New Product") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            if (displayError != null) {
                Surface(
                    color = MaterialTheme.colorScheme.errorContainer,
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.fillMaxWidth().padding(bottom = 16.dp)
                ) {
                    Text(
                        text = displayError,
                        color = MaterialTheme.colorScheme.onErrorContainer,
                        modifier = Modifier.padding(16.dp)
                    )
                }
            }

            // Image Picker UI
            Text("Product Image", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
            Spacer(modifier = Modifier.height(8.dp))

            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(180.dp),
                contentAlignment = Alignment.Center
            ) {
                val displayModel = selectedImageUri ?: existingImageUrls.firstOrNull()
                if (displayModel != null) {
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        AsyncImage(
                            model = displayModel,
                            contentDescription = "Selected Image",
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(130.dp)
                                .clip(RoundedCornerShape(12.dp)),
                            contentScale = ContentScale.Crop
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        TextButton(onClick = { imagePickerLauncher.launch("image/*") }) {
                            Text("Change Image")
                        }
                    }
                } else {
                    OutlinedButton(
                        onClick = { imagePickerLauncher.launch("image/*") },
                        modifier = Modifier.fillMaxWidth().height(80.dp),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.Add, contentDescription = "Upload Image")
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Select Image from Gallery")
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            OutlinedTextField(
                value = name,
                onValueChange = {
                    name = it
                    validationError = null
                },
                label = { Text("Product Name *") },
                placeholder = { Text("Enter product name (e.g. Classic T-Shirt)") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true
            )

            Spacer(modifier = Modifier.height(12.dp))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedTextField(
                    value = size,
                    onValueChange = {
                        size = it
                        validationError = null
                    },
                    label = { Text("Exact Size *") },
                    placeholder = { Text("e.g. M, L, 32") },
                    modifier = Modifier.weight(1f),
                    singleLine = true
                )

                OutlinedTextField(
                    value = color,
                    onValueChange = {
                        color = it
                        validationError = null
                    },
                    label = { Text("Exact Color *") },
                    placeholder = { Text("e.g. Black, Navy") },
                    modifier = Modifier.weight(1f),
                    singleLine = true
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Auto-generated Product Code field (Read-only)
            OutlinedTextField(
                value = autoGeneratedCode,
                onValueChange = {},
                label = { Text("Auto-Generated Product Code") },
                placeholder = { Text("Fill Name, Size & Color to generate code") },
                enabled = false,
                modifier = Modifier.fillMaxWidth(),
                colors = OutlinedTextFieldDefaults.colors(
                    disabledTextColor = MaterialTheme.colorScheme.primary,
                    disabledBorderColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.5f),
                    disabledLabelColor = MaterialTheme.colorScheme.onSurfaceVariant
                ),
                singleLine = true
            )

            Spacer(modifier = Modifier.height(12.dp))

            OutlinedTextField(
                value = category,
                onValueChange = {
                    category = it
                    validationError = null
                },
                label = { Text("Category *") },
                placeholder = { Text("Enter category (e.g. T-Shirts, Jeans)") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true
            )

            Spacer(modifier = Modifier.height(12.dp))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedTextField(
                    value = priceInput,
                    onValueChange = {
                        priceInput = it
                        validationError = null
                    },
                    label = { Text("Price (Rs.) *") },
                    placeholder = { Text("Enter price e.g. 3500") },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                    modifier = Modifier.weight(1f),
                    singleLine = true
                )

                OutlinedTextField(
                    value = stockInput,
                    onValueChange = {
                        stockInput = it
                        validationError = null
                    },
                    label = { Text("Initial Stock Quantity *") },
                    placeholder = { Text("Enter stock e.g. 10") },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                    modifier = Modifier.weight(1f),
                    singleLine = true
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            OutlinedTextField(
                value = description,
                onValueChange = { description = it },
                label = { Text("Description") },
                placeholder = { Text("Enter product details...") },
                modifier = Modifier.fillMaxWidth(),
                maxLines = 3
            )

            Spacer(modifier = Modifier.height(12.dp))

            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text("Product Active Status", fontWeight = FontWeight.Bold)
                Switch(
                    checked = active,
                    onCheckedChange = { active = it }
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Generate & Preview Product QR
            Button(
                onClick = {
                    if (autoGeneratedCode.isNotBlank()) {
                        viewModel.generateProductQr(autoGeneratedCode)
                    } else {
                        validationError = "Please enter Product Name, Size, and Color to generate QR."
                    }
                },
                modifier = Modifier.fillMaxWidth(),
                colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.secondary),
                enabled = autoGeneratedCode.isNotBlank()
            ) {
                Text("Generate Product QR")
            }

            uiState.generatedQrBitmap?.let { qrBitmap ->
                Spacer(modifier = Modifier.height(16.dp))
                Column(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Image(
                        bitmap = qrBitmap.asImageBitmap(),
                        contentDescription = "Generated QR",
                        modifier = Modifier.size(180.dp)
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Code: $autoGeneratedCode", style = MaterialTheme.typography.bodySmall, fontWeight = FontWeight.Bold)

                    Spacer(modifier = Modifier.height(8.dp))

                    OutlinedButton(
                        onClick = {
                            QrDownloadUtil.saveQrCodeToDownloads(
                                context = context,
                                qrBitmap = qrBitmap,
                                productName = name.ifBlank { "Product" },
                                productCode = autoGeneratedCode
                            )
                        }
                    ) {
                        Text("Download QR PNG")
                    }
                }
            }

            Spacer(modifier = Modifier.height(32.dp))

            Button(
                onClick = {
                    if (name.isBlank() || size.isBlank() || color.isBlank() || category.isBlank() || priceInput.isBlank() || stockInput.isBlank()) {
                        validationError = "Please fill in all required fields (Name, Size, Color, Category, Price, Stock)."
                        return@Button
                    }

                    val price = priceInput.toDoubleOrNull()
                    if (price == null || price < 0) {
                        validationError = "Please enter a valid price."
                        return@Button
                    }

                    val stock = stockInput.toIntOrNull()
                    if (stock == null || stock < 0) {
                        validationError = "Please enter a valid stock quantity."
                        return@Button
                    }

                    validationError = null

                    viewModel.saveProductWithImage(
                        productId = productId ?: "",
                        name = name,
                        productCode = autoGeneratedCode,
                        description = description,
                        category = category,
                        size = size,
                        color = color,
                        price = price,
                        stockQuantity = stock,
                        imageBytes = imageBytes,
                        existingImageUrls = existingImageUrls,
                        active = active
                    )
                },
                modifier = Modifier.fillMaxWidth().height(50.dp),
                enabled = !uiState.isLoading
            ) {
                if (uiState.isLoading) {
                    CircularProgressIndicator(color = MaterialTheme.colorScheme.onPrimary, modifier = Modifier.size(24.dp))
                } else {
                    Text(if (isEditMode) "Update Product" else "Save Product to Store")
                }
            }
        }
    }
}
